name: Specs

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
  specs:
    name: Test with Pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
    
      - name: Test with Pytest
        run: |
          python -m pytest -v --disable-warnings
